### PR TITLE
gpasswd.c: fix memory leak in sg_adm

### PR DESCRIPTION
**Pull request by whzhe51**
Signed-off-by: whzhe <wanghongzhe@huawei.com>

### CODE REVIEW

**Comment by brauner** [comment]
This looks reasonable to me. I'll let @hallyn take a loo at it too.

**Review by brauner — APPROVED** [review]
Looks reasonable to me!

**Comment by hallyn** [comment]
Hm, so why sg_adm, but not sg_mem, and why not the grent-> ones?

Note this patch as is will break compile if !SHADOWGRP.

But I'm also failing to see the point, since it's right before exit.

**Comment by whzhe51** [comment]
> Hm, so why sg_adm, but not sg_mem, and why not the grent-> ones?
> 
> Note this patch as is will break compile if !SHADOWGRP.
> 
> But I'm also failing to see the point, since it's right before exit.

I think you are right，and i fix the commits.

**Comment by whzhe51** [comment]
> Hm, so why sg_adm, but not sg_mem, and why not the grent-> ones?
> 
> Note this patch as is will break compile if !SHADOWGRP.
> 
> But I'm also failing to see the point, since it's right before exit.

I think you are right, and i will fix the mr.

**Pull request merged**
