### PR TITLE
Add alloc.h and bit.h to libmisc_la_SOURCES

### PR DESCRIPTION
**Pull request by jubalh**
See https://github.com/shadow-maint/shadow/issues/763

### CODE REVIEW

**Comment by jubalh** [comment]
@alejandro-colomar could you check this?
Also see https://github.com/shadow-maint/shadow/issues/763#issuecomment-1664383425 why they are in different dirs?

**Comment by alejandro-colomar** [comment]
I didn't know the build system of this project very much.  I just built following the instructions in my system and it seemed to work, so I left it that way.  How did you build to notice those issues?  Maybe you can post that in the new <https://github.com/shadow-maint/shadow/blob/master/doc/contributions/build_install.md>, or point me to it if it's already documented and I missed it?

If you patch fixes this, I guess `Acked-by: Alejandro Colomar <alx@kernel.org>`

Please add `Fixes: hash ("commit message")` tags for the commits it fixes.

Thanks for fixing my bugs! :-)

**Comment by alejandro-colomar** [comment]
As to why they are in different dirs, I don't know how these libs should be organized ideally.  Feel free to move them if that's better.  I agree that having the header in lib and the source in libmisc is weird.  But I think I checked before doing that and found some case where it already happened (or something similar) and imitated it; can't tell for sure.

**Comment by ikerexxe** [comment]
One minor comment, I'd change the commit message from `See https://github.com/shadow-maint/shadow/issues/763`to `Resolves: https://github.com/shadow-maint/shadow/issues/763`

Apart from that I'd like @hallyn to check that this actually includes the missing files in the compressed file.

**Comment by hallyn** [comment]
@alejandro-colomar  yes we should add a check to CI which does 'make dist' followed by an attempt to build from the resulting tarball, to catch things like this.

**Comment by jubalh** [comment]
>  I just built following the instructions in my system and it seemed to work, so I left it that way. How did you build to notice those issues? 

I was testing it on our [build system](https://build.opensuse.org/package/show/home:jubalh:branches:Base:System/shadow).

> One minor comment, I'd change the commit message from See https://github.com/shadow-maint/shadow/issues/763to Resolves: https://github.com/shadow-maint/shadow/issues/763

I wasn't sure if it's the best fix and why the files were missing and thus opted for a related. But I'll change that :)

What's confusing me though is that  CI for PR 777 builds fine even without this change here. How comes the it doesn't need those header files in libmisc_la_SOURCES and why seem the files not to be missing there but apparently they are in the tarball mentioned above? Confusing :)

**Comment by hallyn** [comment]
https://github.com/shadow-maint/shadow/pull/777  Catches this error.  Do you want to cherrypick that commit from my pr branch into yours and verify that it passes then? :)

**Pull request merged**
