### PR TITLE
src/useradd.c: Add fmkomstemp() to fix mode of </etc/default/useradd>

### PR DESCRIPTION
**Pull request by alejandro-colomar**
The mode of the file should be 644, but mkstemp(2) was transforming it to 600.

To do this, we need a function that accepts a mode parameter.  While we don't need a flags parameter, to avoid confusion with mkostemp(2), let's add both a flags and a mode parameter.

Link: <https://github.com/shadow-maint/shadow/pull/1080>
Reported-by: @kugarocks
Suggested-by: @kugarocks

---

Revisions:

<details>
<summary>v2</summary>

-  Add missing octal prefix [@kugarocks ]

```
$ git range-diff shadow/master gh/fmkostemp fmkostemp 
1:  fd362dfb ! 1:  b0193b2e src/useradd.c: Add fmkomstemp() to fix mode of </etc/default/useradd>
    @@ src/useradd.c: set_defaults(void)
         * Create a temporary file to copy the new output to.
         */
     -  ofp = fmkstemp(new_file);
    -+  ofp = fmkomstemp(new_file, 0, 644);
    ++  ofp = fmkomstemp(new_file, 0, 0644);
        if (NULL == ofp) {
                fprintf (stderr,
                         _("%s: cannot open new defaults file\n"),
```
</details>

<details>
<summary>v3</summary>

-  Use fchmod(2) instead of fchmodat(2).  [@kugarocks ]

```
$ git range-diff shadow/master gh/fmkostemp fmkostemp 
1:  b0193b2e ! 1:  6d3296d0 src/useradd.c: Add fmkomstemp() to fix mode of </etc/default/useradd>
    @@ src/useradd.c: int main (int argc, char **argv)
        if (fd == -1)
                return NULL;
      
    -+  if (fchmodat(fd, "", m, AT_EMPTY_PATH) == -1)
    ++  if (fchmod(fd, m) == -1)
     +          goto fail;
     +
        fp = fdopen(fd, "w");
```
</details>

<details>
<summary>v3b</summary>

-  Tested-by: @kugarocks 

```
$ git range-diff shadow/master gh/fmkostemp fmkostemp 
1:  6d3296d0 ! 1:  5f33ce7a src/useradd.c: Add fmkomstemp() to fix mode of </etc/default/useradd>
    @@ Commit message
         Link: <https://github.com/shadow-maint/shadow/pull/1080>
         Reported-by: kugarocks <kugacola@gmail.com>
         Suggested-by: kugarocks <kugacola@gmail.com>
    +    Tested-by: kugarocks <kugacola@gmail.com>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
      ## src/useradd.c ##
```
</details>

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
I'm wondering if it's okay to hardcode 644, or if we should stat(2) the actual mode of the existing file, to really not modify it.  @hallyn ?

**Comment by alejandro-colomar** [comment]
@kugarocks, would you mind testing this?

**Comment by alejandro-colomar** [comment]
BTW, while the Linux manual page for fchmodat(2) doesn't document AT_EMPTY_PATH, I checked the kernel source code and it supports the flag.  FreeBSD does document the flag.  It would be good if somebody was paid to work full time in the man pages project to have less of these issues.  :)

**Comment by alejandro-colomar** [comment]
BTW, is having the file be 644 under /tmp ok?  I think it is, but am worried about the little implications of the sticky bit, which I don't deal often with.

**Comment by kugarocks** [comment]
> @kugarocks, would you mind testing this?

```c
fchmodat(fd, "", m, AT_EMPTY_PATH)
```

fchmodat: Invalid argument.

**Comment by kugarocks** [comment]
It seem that we can use `fchmod`.

```
fchmod(fd, 0644);
```

But I found that if the mode without the prefix zero `644`, the result is wired.

```
--w----r-T 1 root root 1.6K Sep 29 21:56 /etc/default/useradd
```

**Comment by alejandro-colomar** [comment]
> It seems that we can use `fchmod`.
> 
> ```
> fchmod(fd, 0644);
> ```
> 
> But I found that if the mode is `644` without the prefix zero, the result is wired.
> 
> ```
> --w----r-T 1 root root 1.6K Sep 29 21:56 /etc/default/useradd
> ```

Oops, I forgot the octal prefix

**Comment by alejandro-colomar** [comment]
Can you please run this test program in your system?

```c
alx@debian:~/tmp/linux$ cat fmkomstemp.c 
#include <err.h>
#include <fcntl.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>

static FILE * fmkomstemp(char *template, unsigned int flags, mode_t m);

int
main(int argc, char *argv[])
{
	char  fname[PATH_MAX] = "XXXXXXXX";
	if (argc != 2)
		errx(1, "argc");
	if (fmkomstemp(fname, 0, strtol(argv[1], NULL, 0)) == NULL)
		err(1, "fmkomstemp");
	printf("<%s>\n", fname);
}

static FILE *
fmkomstemp(char *template, unsigned int flags, mode_t m)
{
	int   fd;
	FILE  *fp;

	fd = mkostemp(template, flags);
	if (fd == -1)
		return NULL;

	if (fchmodat(fd, "", m, AT_EMPTY_PATH) == -1)
		goto fail;

	fp = fdopen(fd, "w");
	if (fp == NULL)
		goto fail;

	return fp;
fail:
	close(fd);
	unlink(template);
	return NULL;
}

```
```sh
alx@debian:~/tmp/linux$ gcc -Wall -Wextra fmkomstemp.c -D_GNU_SOURCE
alx@debian:~/tmp/linux$ ls
a.out  fmkomstemp.c
alx@debian:~/tmp/linux$ ./a.out 0643
<XX46lxzW>
alx@debian:~/tmp/linux$ ls -l
total 24
-rw-r---wx 1 alx alx     0 Sep 29 16:57 XX46lxzW
-rwxrwxr-x 1 alx alx 16408 Sep 29 16:57 a.out
-rw-rw-r-- 1 alx alx   774 Sep 29 16:57 fmkomstemp.c
```

**Comment by kugarocks** [comment]
> ```shell
> ./a.out 0643
> ```

```bash
root@host:~# ./a.out 0643
a.out: fmkomstemp: Invalid argument
```

**Comment by alejandro-colomar** [comment]
> > ```shell
> > ./a.out 0643
> > ```
> 
> ```shell
> root@host:~# ./a.out 0643
> a.out: fmkomstemp: Invalid argument
> ```
> 
> It works when I specify the file path and remove AT_EMPTY_PATH. It seems that the system doesn't support this flag. BTW the kernel is 5.15.0-113-generic.

Hmmm, it is too new it seems.  I'll use fchmod(2).  Thanks!

**Comment by alejandro-colomar** [comment]
Please test again.  This should work, I hope.  :)

**Comment by kugarocks** [comment]
> Please test again. This should work, I hope. :)

It works fine.

**Comment by alejandro-colomar** [comment]
> > Please test again. This should work, I hope. :)
> 
> It works fine.

Thanks!  I've added `Tested-by: kugarocks <kugacola@gmail.com>`.

**Comment by hallyn** [comment]
Thanks both - looks good.

**Review by hallyn — APPROVED** [review]

**Pull request merged**
