### PR TITLE
Assume C89 is available

### PR DESCRIPTION
**Pull request by alejandro-colomar**
Remove STDC_HEADERS, since C89 is nowadays available everywhere (or at least everywhere we can possibly care).

STDC_HEADERS removal allows to simplify other things.  Propagate those changes.

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
Oops, I started from another branch where I had the strlcpy(3) changes.  I've force-pushed to remove those.

**Comment by alejandro-colomar** [comment]
I wonder if there's any system that defined a locale-dependent isdigit(3).  C89 allows for that, but at least glibc unconditionally defines it to basically the same that we do.

**Comment by hallyn** [comment]
Thank you.  Sorry i forgot to merge this before tagging 4.11.

**Comment by alejandro-colomar** [comment]
No problem, I have more changes pending :)

Thanks!
Alex

**Pull request merged**
