### PR TITLE
Add regression test coverage for 'usermod -rG' (supplemental group removal)

### PR DESCRIPTION
**Pull request by jayaddison**
This attempts to add regression test coverage relating to #561.

## Test info

The configuration here creates two users, `foo` and `bar`:

- Both belong to `users`
- `foo` initially belongs to `floppy`
- `bar` initially belongs to `fax`

The test case uses `usermod -rG` twice, attempting to remove `foo` from _both_ `floppy` (valid) and from `fax` (invalid).

Afterwards the assertions check the group/user state, including that:

- Both users belong to `users`
- `foo` does not belong to any other groups
- `bar` continues to belong to the `fax` group

## Status

:warning: I have managed to get this to succeed locally in a `chroot` using `usermod` from `shadow` v4.13 (with the fix from #560 applied), but I have **not** yet run confirmed that the regression test fails when running with a version where the bug existed.

If anyone can help out with doing that, it'd be much appreciated!

### CODE REVIEW

**Comment by hallyn** [comment]
Please add it also to tests/run_some , as that is the set that CI runs.

Then once that's done, we can just open another draft pr where the fixing commit gets reverted, to verify that it correctly fails.

**Comment by jayaddison** [comment]
Thanks @hallyn - that's done in #594 (draft pr), and I think that that demonstrates the expected test failure (please verify, though).

**Comment by hallyn** [comment]
> 

Sorry I didn't notice 594.  Github tells me that you deleted issue-561/verify-test-coverage, and I don't see the test results, only shellcheck results.  Could you re-push that branch?

**Comment by jayaddison** [comment]
Yep - done; (another) empty commit required to get the continuous integration to run again - pushing that in a few moments.

**Pull request merged**
