### PR TITLE
WIP: Initial bcrypt support

### PR DESCRIPTION
**Pull request by seitokaichou**

### CODE REVIEW

**Comment by hallyn** [comment]
Hi,

the PR subject still says 'WIP'.  Would you still consider this a WIP, or should it be considered for merging?

**Comment by seitokaichou** [comment]
Very much WIP, and still untested.
Do you want me to do the manpages and tests in a seperate PR? In case you do, the tests might take me a while because I don't have much experience with those.

**Comment by seitokaichou** [comment]
@hallyn I marked this as "ready for review" now.
`chpasswd` has been briefly tested on my musl machine.

**Comment by hallyn** [comment]
Thank you

**Pull request merged**
