### PR TITLE
chage.c: add support for YYYY-MM-DD date printing

### PR DESCRIPTION
**Pull request by edneville**
New option to print dates in ISO format.

EDIT: For clarity, iso8601 date format to match date input formats (YYYY-MM-DD). The intention here is to provide consistency between date display and input.

### CODE REVIEW

**Comment by glensc** [comment]
you probably mean ISO8601, as there are many iso standards :)

**Comment by jubalh** [comment]
He clearly is aware of this otherwise he wouldn't have called the switch `--iso8601`.

**Comment by glensc** [comment]
I'm talking about clickbait descriptions: to actually see that, have to click for the diffs.

**Comment by edneville** [comment]
> I'm talking about clickbait descriptions: to actually see that, have to click for the diffs.

Thanks, updated the description.

**Pull request merged**
