### PR TITLE
lib/, src/: Rename unused macro as MAYBE_UNUSED

### LINKED ISSUE #918: shadow 4.14.2: Build error 'parameter name omitted' in logind
I'm getting this error building shadow 4.14.2:

``` sh
/bin/sh ../libtool  --tag=CC   --mode=compile gcc   -I. -I../../../../../../../workspace/sources/shadow-native/lib -I..    -I../../../../../../../workspace/sources/shadow-native -isystem/tmp/work/x86_64-linux/shadow-native/4.14.2/recipe-sysroot-native/usr/include -DLIBBSD_OVERLAY -isystem /tmp/work/x86_64-linux/shadow-native/4.14.2/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/include/bsd  -lsystemd -isystem/tmp/work/x86_64-linux/shadow-native/4.14.2/recipe-sysroot-native/usr/include -O2 -pipe -MT libshadow_la-logind.lo -MD -MP -MF .deps/libshadow_la-logind.Tpo -c -o libshadow_la-logind.lo `test -f 'logind.c' || echo '../../../../../../../workspace/sources/shadow-native/lib/'`logind.c
libtool: compile:  gcc -I. -I../../../../../../../workspace/sources/shadow-native/lib -I.. -I../../../../../../../workspace/sources/shadow-native -isystem/tmp/work/x86_64-linux/shadow-native/4.14.2/recipe-sysroot-native/usr/include -DLIBBSD_OVERLAY -isystem /tmp/work/x86_64-linux/shadow-native/4.14.2/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/include/bsd -lsystemd -isystem/tmp/work/x86_64-linux/shadow-native/4.14.2/recipe-sysroot-native/usr/include -O2 -pipe -MT libshadow_la-logind.lo -MD -MP -MF .deps/libshadow_la-logind.Tpo -c ../../../../../../../workspace/sources/shadow-native/lib/logind.c  -fPIC -DPIC -o .libs/libshadow_la-logind.o
../../../../../../../workspace/sources/shadow-native/lib/logind.c: In function �~@~Xactive_sessions_count�~@~Y:
../../../../../../../workspace/sources/shadow-native/lib/logind.c:38:55: error: parameter name omitted
   38 | unsigned long active_sessions_count(const char *name, unsigned long unused)
```
I am using `gcc (Debian 10.2.1-6) 10.2.1 20210110` in this context.

The following patch fix the error but I am not 100% sure if this is the exected:

``` diff
diff --git a/lib/logind.c b/lib/logind.c
index d4d217c..da945d6 100644
--- a/lib/logind.c
+++ b/lib/logind.c
@@ -35,7 +35,7 @@ done:
     return ret;
 }
 
-unsigned long active_sessions_count(const char *name, unsigned long unused)
+unsigned long active_sessions_count(const char *name, unsigned long unused _)
 {
     struct passwd *pw;
     unsigned long count = 0;
```

### PR DESCRIPTION
**Pull request by psaavedra**
Also fixes #918 by adding the omitted parameter name in active_sessions_count.

Suggested-by: Alejandro Colomar <alx@kernel.org>

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
Please split the commit into two separate commits.  One for renaming the macro, and one for naming the parameter.

**Comment by psaavedra** [comment]
> Please split the commit into two separate commits. One for renaming the macro, and one for naming the parameter.

Yes, makes much more send. Done.

**Review by alejandro-colomar — DISMISSED** [review]

**Comment by alejandro-colomar** [comment]
I've been thinking...  Would you mind renaming the macro to `MAYBE_UNUSED` instead of just `UNUSED`?  That's the name that the ISO C23 attribute has, and UNUSED() is a macro name that's sometimes used for something different: discarding the return value of an expression.,

**Comment by alejandro-colomar** [comment]
And I also see something inconsistent (not your fault): sometimes we say `int unused(x)` and others we say `unused int x`.  I'd like to use the second form always.  Would you mind writing a separate patch that makes the use of this macro consistent?

Thanks!

**Comment by psaavedra** [comment]
PR updated with the suggestions from @alejandro-colomar.

**Review by alejandro-colomar — APPROVED** [review]

**Comment by alejandro-colomar** [comment]
```
Reviewed-by: Alejandro Colomar <alx@kernel.org>
```

**Review by ikerexxe — APPROVED** [review]
LGTM. Thanks for the patch!

**Pull request merged**
