### PR TITLE
Remove code wrapped in USE_NIS; that is, don't use NIS

### PR DESCRIPTION
**Pull request by alejandro-colomar**

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
This PR would make this comment obsolete: <https://github.com/shadow-maint/shadow/commit/9a7f5c6b16ef9d1ca8637a3dcb5e27cd1c5dc372#diff-cfc1a71a8d276e6874357906177011d16928d127f4f639d4ea14050c85f817b4R197>.

**Comment by alejandro-colomar** [comment]
v1b changes:

-  Rebase to master

```
$ git range-diff alx/master..gh/nonis shadow/master..nonis 
1:  8da6d684 = 1:  a29420cf lib/, src/: Remove all code wrapped in defined(USE_NIS)
2:  73988595 = 2:  bc63a4c4 lib/: Clean up after previous removal of dead code
```

**Comment by alejandro-colomar** [comment]
v1c changes:

-  Rebase to master

```
$ git range-diff alx/master..gh/nonis shadow/master..nonis 
1:  a29420cf = 1:  2a6940ee lib/, src/: Remove all code wrapped in defined(USE_NIS)
2:  bc63a4c4 = 2:  aa0bdd9d lib/: Clean up after previous removal of dead code
```

**Comment by alejandro-colomar** [comment]
v1d changes:

-  Rebase to master

```
$ git range-diff gh/master..gh/nonis    alx/master..nonis 
1:  2a6940ee = 1:  1a1609d3 lib/, src/: Remove all code wrapped in defined(USE_NIS)
2:  aa0bdd9d = 2:  888c1be3 lib/: Clean up after previous removal of dead code
```

**Review by hallyn — APPROVED** [review]
Bold.

**Comment by alejandro-colomar** [comment]
> Bold.

I got back my negative net line count with this.  =)

**Pull request merged**
