### PR TITLE
Use safer and simpler string copy functions. (v2)

### PR DESCRIPTION
**Pull request by alejandro-colomar**
This is a continuation of <https://github.com/shadow-maint/shadow/pull/569>.

For auditability, I'm initially opening it at commit <https://github.com/shadow-maint/shadow/commit/49fcdcf95f7c3dd2f94ea4df3946ec0d020c2edd>.

Now at least I can mark it as a draft :)

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
Rebased to master.

**Comment by alejandro-colomar** [comment]
Important notice:

<https://lore.kernel.org/linux-man/73f64795-b4fe-956c-c20b-8e2a1fa05929@gmail.com/T/#mb1a5b24d49fd52081f7f8cc432ab29183ab8cd30>

I CCed the shadow-utils mailing list, but since I'm not subscribed, it bounced to me.  Please check the ML archive from linux-man@ linked above.

I didn't check `strncat(3)` when I started this PR.  It is evil, like `strncpy(3)`, although in a very different way (they are not related at all).

I'll update this PR to cover that.

**Comment by alejandro-colomar** [comment]
Hi!

I've been working on a document that describes correct use of string copying functions.
I've been surprised by a few of them.
It covers all the functions provided by libcs (except for the obsolete Annex K ones --those with `_s`--), plus some custom ones.

I'll take the document into consideration for this PR.
BTW, if you have a look into it before I release it in the Linux man-pages, and give some feedback, it would be nice :)

Cheers,

Alex

```
string_copy(7)         Miscellaneous Information Manual         string_copy(7)

NAME
       string_copy - copy and concatenate strings

SYNOPSIS
   (Null‐terminated) strings
       // Copy a string (can overrun).
       char *strcpy(char *restrict dst, const char *restrict src);

       // Copy a string with truncation.
       size_t strlcpy(char dst[restrict .sz], const char *restrict src,
                      size_t sz);

       // Copy an untrusted string with truncation.
       ssize_t strscpy(char dst[restrict .sz], const char src[restrict .sz],
                      size_t sz);

       // Chain‐copy a string (can overrun).
       char *stpcpy(char *restrict dst, const char *restrict src);

       // Chain‐copy a string with truncation.
       char *stpecpy(char *dst, const char *restrict src,
                      char past_end[0]);

       // Concatenate a string (can overrun; performance issues).
       char *strcat(char *restrict dst, const char *restrict src);

       // Concatenate a string with truncation (performance issues).
       size_t strlcat(char dst[restrict .sz], const char *restrict src,
                      size_t sz);

   Unterminated strings and fixed‐width buffers
       // Zero a fixed‐width buffer, and
       // chain‐copy a string with truncation into an unterminated string.
       char *stpncpy(char dst[restrict .len], const char *restrict src,
                      size_t len);

       // Chain‐copy an unterminated string into a string (can overrun).
       char *ustr2stp(char *restrict dst, const u_char src[restrict .len],
                      size_t len);

       // Chain‐copy a fixed‐width unterminated string into a string
       // (can overrun).
       char *fwustr2stp(char *restrict dst, const u_char src[restrict .sz],
                      size_t sz);

       // Concatenate a fixed‐width unterminated string into a string
       // (can overrun).
       char *strncat(char *restrict dst, const char src[restrict .len],
                      size_t len);

   String structure
       struct str_s {
           size_t  sz;
           char    *str;
       };

       // Chain‐copy a string structure into a string.
       char *sts2stp(char *restrict dst, const struct str_s *restrict src);

   Unterminated string structure (overlapping strings)
       struct ustr_s {
           size_t  len;
           u_char  *ustr;
       };

       // Chain‐copy an unterminated string structure into a string.
       char *usts2stp(char *restrict dst, const struct ustr_s *restrict src);

       // Chain‐copy an unterminated string structure.
       u_char *usts2ustp(u_char *restrict dst,
                      const struct ustr_s *restrict src);

   Obsolete functions
       // Zero a fixed‐width buffer, and
       // chain‐copy a string with truncation into an unterminated string
       // (can’t detect truncation).
       [[deprecated]]
       char *strncpy(char dest[restrict .len], const char *restrict src,
                      size_t len);

DESCRIPTION
   Terms (and abbreviations)
       string (str)
              is a sequence of zero or more non‐null characters, followed by a
              null character.

       length (len)
              is the number of non‐null characters in a string.

       size (sz)
              refers to the entire buffer where the string is contained; it is
              equivalent to length + 1.

       unterminated string (ustr)
              is  a sequence of zero or more non‐null characters.  They have a
              length, but not a size.  They are sometimes contained in  fixed‐
              width buffers, which usually contain null bytes after the unter‐
              minated string, to fill the rest of the buffer without affecting
              the  unterminated string; however, those null bytes are not part
              of the unterminated string.

       string structure (sts)
              Structure that contains the size of a string,  as  well  as  the
              string itself.

       unterminated string structure (usts)
              Similar to the string structure, but it contains an unterminated
              string.

   Types of functions
       Copy, concatenate, and chain‐copy
              Originally,  there was a distinction between functions that copy
              and those that concatenate.  However, newer functions that  copy
              while  allowing chaining cover both use cases with a single API.
              They are also algorithmically faster, since they don’t  need  to
              search for the end of the existing string.

              To  chain  copy  functions, they need to return a pointer to the
              terminating null character, or to one after the  last  character
              in  the case of unterminated strings.  That’s a byproduct of the
              copy operation, so it has no performance costs.

              Functions that return such a pointer, and thus can  be  chained,
              have names of the form *stp*().

       Overrun or truncate
              When  copying  strings,  there’s  a choice: overrun or truncate?
              When the source string is longer than the destination buffer,  a
              decision has to be made.

              The  first thing to note is that programmers should take care of
              buffers, so they always have the correct size.  This  is  diffi‐
              cult  if  there isn’t a consistent handling of strings, and many
              security flaws have been caused by this issue.

              There’s controversy about which is preferable.  Original  string
              copy  functions  in  C  chose to overrun, since they are simpler
              (both their implementation and their use), since  the  functions
              act unrestricted, assuming that the programmer has made sure the
              program  is  correct (that may be assuming too much, of course).
              They were also faster, since they don’t do bounds checks.

              Programmers always make mistakes, but that must be assumed; pro‐
              gramming against those mistakes by adding more  code  just  adds
              more points where mistakes can be made.

              Nowadays,  compilers can detect most programmer errors with fea‐
              tures   like   compiler   warnings,   static   analyzers,    and
              _FORTIFY_SOURCE  (see  ftm(7)).   Keeping  the code simple helps
              these error‐detection features be more precise.

              And of course, programs should stay readable,  maximizing  self‐
              documentation,  for  which  using the most appropriate (special‐
              ized) APIs is better than using generic APIs.

              Functions that truncate:

              •  strlcpy(3bsd) and strlcat(3bsd), which originated in OpenBSD,
                 are designed to crash if the input string is invalid (doesn’t
                 contain a null character).

              •  strscpy(9) is a function in the Linux  kernel  that  takes  a
                 string that should be terminated but it’s not known with cer‐
                 tainty.  If the string is truncated, an error is reported in‐
                 stead of crashing.

              •  stpecpy()  is similar to strscpy(9), but allows chaining.  It
                 is defined as:

                     inline
                     char *
                     stpecpy(char *dst,
                             const char *restrict src,
                             char past_end[0])
                     {
                         char *p;

                         if (dst == past_end)
                             return past_end;

                         p = memccpy(dst, src, '\0', past_end - dst);
                         if (p != NULL)
                             return p - 1;

                         /* truncation detected */
                         past_end[-1] = '\0';
                         return past_end;
                     }

              •  stpncpy(3) (and strncpy(3)) also  truncate,  but  they  don’t
                 write strings, but rather unterminated strings.

   Unterminated strings and fixed‐width buffers
       For  historic reasons, some standard APIs, such as utmpx(5), use unter‐
       minated strings in fixed‐width buffers.  To interface with  them,  spe‐
       cialized functions need to be used.

       To copy strings into them, use stpncpy(3).

       To  copy  from an unterminated string into a string, you should use the
       following function:

           inline
           char *
           ustr2stp(char *restrict dst, const u_char *restrict src, size_t len)
           {
               memcpy(dst, src, len);
               dst[len] = '\0';

               return dst + len;
           }

       If the unterminated string is in a fixed‐width buffer, we need  to  get
       rid of the extra null bytes:

           inline
           char *
           fwustr2stp(char *restrict dst, const u_char *restrict src, size_t sz)
           {
               char  *end;

               end = mempcpy(dst, src, strnlen((const char *) src, sz));
               *end = '\0';

               return end;
           }

   String structure
       The  simplest  byte copying function is memcpy(3).  Working with it di‐
       rectly is confusing, and error‐prone.  But it will allow  the  compiler
       have  more  knowledge  of the changes applied to strings, and also keep
       your program fast and simple.  Using a string structure and  APIs  that
       wrap  around  memcpy(3)  can make the code clear to both the programmer
       and the compiler.

       The following function can be used to chain‐copy from a  string  struc‐
       ture into a string:

           inline
           char *
           sts2stp(char *restrict dst, const struct str_s *restrict src)
           {
               return mempcpy(dst, src->str, src->sz) - 1;
           }

   Unterminated string structure (overlapping strings)
       In  programs  that  make considerable use of strings, and need the best
       performance, overlapping strings can make a big difference.  It  allows
       holding  substrings of a bigger string while not duplicating memory nor
       using time to do a copy.

       However,  this  is  delicate,  since  it  requires  using  unterminated
       strings.   libc  APIs  use  strings,  so programs that use unterminated
       strings will have to take care to differentiate strings  from  untermi‐
       nated  strings.   A  possible  approach is to use char for strings, and
       u_char for unterminated strings.  With that  convention,  the  compiler
       will  be  able  to  tell  when you use one in place of another, with no
       overhead.

       The following functions can be used to chain‐copy from an  unterminated
       string to a string or an unterminated string:

           inline
           char *
           usts2stp(char *restrict dst, const struct ustr_s *restrict src)
           {
               memcpy(dst, src->ustr, src->len);
               dst[src->len] = '\0';

               return dst + src->len;
           }

           inline
           u_char *
           usts2ustp(u_char *restrict dst, const struct ustr_s *restrict src)
           {
               return mempcpy(dst, src->ustr, src->len);
           }

CAVEATS
       The  following  functions  are  not provided by any library; you should
       write your own copy if you want to use them.

       •  strscpy (9)

       •  strpecpy ()

       •  ustr2stp ()

       •  fwustr2stp ()

       •  sts2stp ()

       •  usts2stp ()

       •  usts2ustp ()

BUGS
       strncpy(3) is identical to stpncpy(3),  except  that  it  can’t  detect
       truncation.  Always use the latter.

SEE ALSO
       stpcpy(3),   stpncpy(3),  strcat(3),  strcpy(3),  strlcat(3bsd),  strl‐
       cpy(3bsd), strncat(3), strscpy(9)

Linux man‐pages (unreleased)        (date)                      string_copy(7)
```

**Comment by hallyn** [comment]
> Hi!
> 
> I've been working on a document that describes correct use of string copying functions. I've been surprised by a few of them. It covers all the functions provided by libcs (except for the obsolete Annex K ones --those with `_s`--), plus some custom ones.
> 
> I'll take the document into consideration for this PR. BTW, if you have a look into it before I release it in the Linux man-pages, and give some feedback, it would be nice :)


Do you have a git branch/pr where we can comment?

**Comment by alejandro-colomar** [comment]
> > Hi!
> > I've been working on a document that describes correct use of string copying functions. I've been surprised by a few of them. It covers all the functions provided by libcs (except for the obsolete Annex K ones --those with `_s`--), plus some custom ones.
> > I'll take the document into consideration for this PR. BTW, if you have a look into it before I release it in the Linux man-pages, and give some feedback, it would be nice :)
> 
> Do you have a git branch/pr where we can comment?

I've done a lot of updates.  Next version I send to the mailing list (maybe tomorrow), I'll add you to the CC.  Thanks!

**Comment by alejandro-colomar** [comment]
Rebased to master

**Pull request closed without merging**
