### PR TITLE
src/su.c: do_check_perms(): Fix -Wincompatible-pointer-types bug

### PR DESCRIPTION
**Pull request by alejandro-colomar**
Fixes: ef95bb7ed139 ("src/su.c: Fix type of variable")
Closes: <https://github.com/shadow-maint/shadow/issues/915>
Reported-by: @thesamesam 
Signed-off-by: @alejandro-colomar

### CODE REVIEW

**Comment by thesamesam** [comment]
Consider fixing CI too to add the other warnings-to-become-errors (https://wiki.gentoo.org/wiki/Modern_C_porting#What_changed.3F), as it would've found this?

**Comment by alejandro-colomar** [comment]
> Consider fixing CI too to add the other warnings-to-become-errors (https://wiki.gentoo.org/wiki/Modern_C_porting#What_changed.3F), as it would've found this?

Yes, I want to do that.  However, considering how much I've DoSed @hallyn and @ikerexxe with the current queue of hardening fixes, I'd like to give them a break (at least merge all the patches I've already sent) before that.  And maybe GCC 14 releases before that, and I don't need to do it.  :)

**Comment by thesamesam** [comment]
Well, then you end up with someone having to file a bug like this, possibly after it made it into a release. But I understand, sure.

**Comment by ikerexxe** [comment]
LGTM!

**Comment by ikerexxe** [comment]
I don't have permissions to `rebase and merge`. Please feel free to do it on your own.

**Comment by alejandro-colomar** [comment]
I see this:

```
Merging is blocked
Merging can be performed automatically with 1 approving review.
```

I guess you need to click on approve.

**Review by ikerexxe — APPROVED** [review]

**Comment by ikerexxe** [comment]
> I guess you need to click on approve.

:facepalm: My bad

**Pull request merged**
