### PR TITLE
Remove support for rlogind in login(1), that is, remove the '-r' flag

### PR DESCRIPTION
**Pull request by alejandro-colomar**
The "quick hack" finally disappeared.  Probably nobody noticed.  ;) (See the changes in <configure.ac> for the context of this pun.)

Probably everybody uses SSH these days for remote login.  Let's remove this insecure functionality.

Closes: <https://github.com/shadow-maint/shadow/issues/992>
Cc: @hallyn 
Cc: @ikerexxe 
Cc: @jubalh 
Cc: @thesamesam 
Cc: @dataCobra
Cc: @dkwo

---

Revisions:

<details>
<summary>v1b</summary>

-  Rebase

```
$ git range-diff master..gh/rlogin shadow/master..rlogin 
1:  1dab33d9 = 1:  f0306cbf Remove support for rlogind in login(1), that is, remove the '-r' flag
```
</details>

<details>
<summary>v1c</summary>

-  Rebase

```
$ git range-diff master..gh/rlogin shadow/master..rlogin 
1:  f0306cbf ! 1:  2aad6592 Remove support for rlogind in login(1), that is, remove the '-r' flag
    @@ src/login.c: int main (int argc, char **argv)
        }
     -#ifdef RLOGIN
     -  if (rflg) {
    --          size_t  max_size = sysconf(_SC_LOGIN_NAME_MAX);
    +-          size_t  max_size;
     -
    +-          max_size = login_name_max_size();
     -          assert (NULL == username);
     -          username = XMALLOC(max_size, char);
     -          username[max_size - 1] = '\0';
```
</details>

<details>
<summary>v1d</summary>

-  Reviewed by @dkwo 

```
$ git range-diff shadow/master gh/rlogin rlogin 
1:  2aad6592 ! 1:  65265b0c Remove support for rlogind in login(1), that is, remove the '-r' flag
    @@ Commit message
         this insecure method.
     
         Closes: <https://github.com/shadow-maint/shadow/issues/992>
    +    Reviewed-by: dkwo <nicolopiazzalunga@gmail.com>
         Cc: "Serge E. Hallyn" <serge@hallyn.com>
         Cc: Iker Pedrosa <ipedrosa@redhat.com>
         Cc: Michael Vetter <jubalh@iodoru.org>
         Cc: Sam James <sam@gentoo.org>
         Cc: Benedikt Brinkmann <datacobra@thinkbot.de>
    -    Cc: dkwo <nicolopiazzalunga@gmail.com>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
      ## configure.ac ##
```
</details>

<details>
<summary>v1e</summary>

-  Rebase

```
$ git range-diff master..gh/rlogin shadow/master..rlogin 
1:  65265b0c = 1:  14d98ddc Remove support for rlogind in login(1), that is, remove the '-r' flag
```
</details>

<details>
<summary>v1f</summary>

-  Rebase
-  Reviewed-by @ikerexxe 

```
$ git range-diff master..gh/rlogin shadow/master..rlogin 
1:  14d98ddc ! 1:  7c6b5d6c Remove support for rlogind in login(1), that is, remove the '-r' flag
    @@ Commit message
     
         Closes: <https://github.com/shadow-maint/shadow/issues/992>
         Reviewed-by: dkwo <nicolopiazzalunga@gmail.com>
    +    Reviewed-by: Iker Pedrosa <ipedrosa@redhat.com>
         Cc: "Serge E. Hallyn" <serge@hallyn.com>
    -    Cc: Iker Pedrosa <ipedrosa@redhat.com>
         Cc: Michael Vetter <jubalh@iodoru.org>
         Cc: Sam James <sam@gentoo.org>
         Cc: Benedikt Brinkmann <datacobra@thinkbot.de>
```
</details>

### CODE REVIEW

**Comment by dkwo** [comment]
Looks good to me, thanks!

**Comment by alejandro-colomar** [comment]
> Looks good to me, thanks!

May I take that as a `Reviewed-by: ...`?

Thank you for checking!

**Comment by dkwo** [comment]
Yes.

**Review by ikerexxe — COMMENTED** [review]
I wonder if we could remove `PW_RLOGIN` and [this line of code](https://github.com/shadow-maint/shadow/blob/master/src/login.c#L573) with it. `reason` is already set to `PW_TELNET` previously, and that makes more sense.

**Comment by alejandro-colomar** [comment]
> I wonder if we could remove `PW_RLOGIN` and [this line of code](https://github.com/shadow-maint/shadow/blob/master/src/login.c#L573) with it. `reason` is already set to `PW_TELNET` previously, and that makes more sense.

I have a patch for removing telnet support (thus, removing `-h`) for when this one is merged.  That one removes those two lines (and much more).

**Comment by ikerexxe** [comment]
> I have a patch for removing telnet support (thus, removing `-h`) for when this one is merged. That one removes those two lines (and much more; even the `reason` variable is removed).

Good!

I think these changes are fine, but I'd like @hallyn to review whether we can remove this functionality.

**Review by ikerexxe — APPROVED** [review]

**Comment by alejandro-colomar** [comment]
Hi Iker, Serge,

On Tue, Jun 11, 2024 at 07:57:17AM GMT, Iker Pedrosa wrote:
> > I have a patch for removing telnet support (thus, removing `-h`) for when this one is merged. That one removes those two lines (and much more; even the `reason` variable is removed).
> 
> Good!
> 
> I think these changes are fine, but I'd like @hallyn to review whether we can remove this functionality.

Thanks!  Serge, please have a look at this.

Have a lovely day!
Alex

> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/shadow-maint/shadow/pull/998#issuecomment-2160979684
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
<https://www.alejandro-colomar.es/>

**Comment by alejandro-colomar** [comment]
@iker, @hallyn, please don't merge yet.

**Comment by alejandro-colomar** [comment]
Since we have breaking changes in master already, there's no point in delaying this for after 4.16.0.  @hallyn, I'll let you merge, since you're preparing the release.

**Pull request merged**
