### PR TITLE
Z2

### PR DESCRIPTION
**Pull request by alejandro-colomar**
Queued after <https://github.com/shadow-maint/shadow/pull/861> (done)

### CODE REVIEW

**Review by ikerexxe — COMMENTED** [review]
Can you move the comments before the macro definition? This would make them more intuitive to read.

**Comment by ikerexxe** [comment]
> Update the documentation, and improve the example, which was rather confusing.

Perhaps adding unit tests would help you explain better how to use it.

**Comment by alejandro-colomar** [comment]
v1c changes:

-  Rebase to master

```
$ git range-diff gh/z2^..gh/z2 shadow/master..z2 
1:  535e3f65 = 1:  2c82fa27 lib/string/zustr2stp.[ch]: Remove zustr2stp(); keep ZUSTR2STP()
```

**Comment by alejandro-colomar** [comment]
v2b changes:

-  Fix check of return value of strcmp(3) in tests

```
$ git range-diff shadow/master gh/z2 z2 
1:  0804e89c = 1:  0804e89c lib/string/zustr2stp.[ch]: Remove zustr2stp(); keep ZUSTR2STP()
2:  32e48544 ! 2:  4ac1d4ab tests/unit/test_zustr2stp.c: Test ZUSTR2STP()
    @@ tests/unit/test_zustr2stp.c (new)
     +  char  dst[4];
     +
     +  ZUSTR2STP(&dst, src);
    -+  assert(strcmp("123", dst));
    ++  assert(strcmp("123", dst) == 0);
     +
     +  src[2] = '\0';
     +  ZUSTR2STP(&dst, src);
    -+  assert(strcmp("12", dst));
    ++  assert(strcmp("12", dst) == 0);
     +
     +  src[1] = '\0';
     +  ZUSTR2STP(&dst, src);
    -+  assert(strcmp("1", dst));
    ++  assert(strcmp("1", dst) == 0);
     +
     +  src[0] = '\0';
     +  ZUSTR2STP(&dst, src);
    -+  assert(strcmp("", dst));
    ++  assert(strcmp("", dst) == 0);
     +}
```

**Comment by alejandro-colomar** [comment]
v3 changes:

-  Test return value of ZUSTR2STP().

```
$ git range-diff shadow/master gh/z2 z2 
1:  0804e89c = 1:  0804e89c lib/string/zustr2stp.[ch]: Remove zustr2stp(); keep ZUSTR2STP()
2:  4ac1d4ab ! 2:  043bd9d3 tests/unit/test_zustr2stp.c: Test ZUSTR2STP()
    @@ tests/unit/test_zustr2stp.c (new)
     +  char  src[3] = {'1', '2', '3'};
     +  char  dst[4];
     +
    -+  ZUSTR2STP(&dst, src);
    ++  assert(ZUSTR2STP(&dst, src) == dst + strlen("123"));
     +  assert(strcmp("123", dst) == 0);
     +
     +  src[2] = '\0';
    -+  ZUSTR2STP(&dst, src);
    ++  assert(ZUSTR2STP(&dst, src) == dst + strlen("12"));
     +  assert(strcmp("12", dst) == 0);
     +
     +  src[1] = '\0';
    -+  ZUSTR2STP(&dst, src);
    ++  assert(ZUSTR2STP(&dst, src) == dst + strlen("1"));
     +  assert(strcmp("1", dst) == 0);
     +
     +  src[0] = '\0';
    -+  ZUSTR2STP(&dst, src);
    ++  assert(ZUSTR2STP(&dst, src) == dst + strlen(""));
     +  assert(strcmp("", dst) == 0);
     +}
```

**Comment by alejandro-colomar** [comment]
v3b changes:

-  Rebase to master

```
$ git range-diff 6fb7fe11..gh/z2 shadow/master..z2 
1:  0804e89c = 1:  f0f7fb11 lib/string/zustr2stp.[ch]: Remove zustr2stp(); keep ZUSTR2STP()
2:  043bd9d3 = 2:  13a54230 tests/unit/test_zustr2stp.c: Test ZUSTR2STP()
```

**Comment by alejandro-colomar** [comment]
v3c changes:

-  Rebase to master

```
$ git range-diff alx/master..gh/z2 shadow/master..z2 
1:  f0f7fb11 = 1:  b5278632 lib/string/zustr2stp.[ch]: Remove zustr2stp(); keep ZUSTR2STP()
2:  13a54230 = 2:  ce03092f tests/unit/test_zustr2stp.c: Test ZUSTR2STP()
```

**Comment by alejandro-colomar** [comment]
v4 changes:

-  Use cmocka's assert_true(); not assert(3).  It shows better in the logs.

```
$ git range-diff gh/master gh/z2 z2 
1:  b5278632 = 1:  b5278632 lib/string/zustr2stp.[ch]: Remove zustr2stp(); keep ZUSTR2STP()
2:  ce03092f ! 2:  f56f0bed tests/unit/test_zustr2stp.c: Test ZUSTR2STP()
    @@ tests/unit/test_zustr2stp.c (new)
     +
     +#include "string/zustr2stp.h"
     +
    -+#undef NDEBUG
    -+#include <assert.h>
    -+
     +
     +static void test_ZUSTR2STP(void **state);
     +
    @@ tests/unit/test_zustr2stp.c (new)
     +  char  src[3] = {'1', '2', '3'};
     +  char  dst[4];
     +
    -+  assert(ZUSTR2STP(&dst, src) == dst + strlen("123"));
    -+  assert(strcmp("123", dst) == 0);
    ++  assert_true(ZUSTR2STP(&dst, src) == dst + strlen("123"));
    ++  assert_true(strcmp("123", dst) == 0);
     +
     +  src[2] = '\0';
    -+  assert(ZUSTR2STP(&dst, src) == dst + strlen("12"));
    -+  assert(strcmp("12", dst) == 0);
    ++  assert_true(ZUSTR2STP(&dst, src) == dst + strlen("12"));
    ++  assert_true(strcmp("12", dst) == 0);
     +
     +  src[1] = '\0';
    -+  assert(ZUSTR2STP(&dst, src) == dst + strlen("1"));
    -+  assert(strcmp("1", dst) == 0);
    ++  assert_true(ZUSTR2STP(&dst, src) == dst + strlen("1"));
    ++  assert_true(strcmp("1", dst) == 0);
     +
     +  src[0] = '\0';
    -+  assert(ZUSTR2STP(&dst, src) == dst + strlen(""));
    -+  assert(strcmp("", dst) == 0);
    ++  assert_true(ZUSTR2STP(&dst, src) == dst + strlen(""));
    ++  assert_true(strcmp("", dst) == 0);
     +}
```

**Comment by alejandro-colomar** [comment]
v4b changes:

-  Rebase to master

```
$ git range-diff gh/master..gh/z2 alx/master..z2 
1:  b5278632 = 1:  86f8964e lib/string/zustr2stp.[ch]: Remove zustr2stp(); keep ZUSTR2STP()
2:  f56f0bed = 2:  6d0bb0b7 tests/unit/test_zustr2stp.c: Test ZUSTR2STP()
```

**Review by hallyn — APPROVED** [review]

**Pull request merged**
