### PR TITLE
updated po file for Dutch

### PR DESCRIPTION
**Pull request by Frans-Spiesschaert**
Hi,
I prepared an updated Dutch translation for shadow version 4.8 (2019-12-01 pot file)
I updated the translation in the first place for Debian, 
but on request of the Debian shadow package maintainer,
Bálint Réczey, I create this pull request.

### CODE REVIEW

**Comment by brauner** [comment]
Hey, thanks for the patch. Can you please remove the merge commit?

**Comment by Frans-Spiesschaert** [comment]
Christian Brauner schreef op do 16-01-2020 om 21:39 [+0000]:
> Hey, thanks for the patch. Can you please remove the merge commit?

Hi,
I'm new to the Github interface. I suppose I messed things up a bit
by creating a new pull request in stead of removing the merge commit.
I feel a bit lost.
-- 
Kind regards,
Frans Spiesschaert

**Comment by hallyn** [comment]
Ok - I'll just hand-apply the patch - thanks.

**Comment by hallyn** [comment]
Actually, it looks like the patch puts nl.po in the top level directory instead of under po/ .  Was that on purpose?  If you like, I can try and fix that up, or we can work together.

**Comment by Frans-Spiesschaert** [comment]
Serge Hallyn schreef op vr 17-01-2020 om 15:52 [+0000]:
> Actually, it looks like the patch puts nl.po in the top level
> directory instead of under po/ . Was that on purpose?
No that wasn't the intention. It has to be put under po/.
>  If you like, I can try and fix that up, or we can work together.
Please, do so, if you would like to.
I'll try to do it right on the next translation update.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
Kind regards,
Frans Spiesschaert

**Comment by hallyn** [comment]
Odd, I was sure I had hit 'merge' on Friday.

**Comment by hallyn** [comment]
Thanks.

**Pull request merged**
