### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by alejandro-colomar**
Signed-off-by: Alejandro Colomar <alx@kernel.org>

### CODE REVIEW

**Comment by ikerexxe** [comment]
LGTM!

Is that all for this PR? If so I'll proceed to merge it.

**Comment by alejandro-colomar** [comment]
I think this is all of it.  Since we were using syslog (AFAICT), there's not much we can remove, apart from the conditionals themselves.

**Comment by alejandro-colomar** [comment]
I still want to remove the funny comment in source code that I introduced, so I'll investigate the `RLOGIN` and `RUSEROK` macros, but in a new PR...

**Comment by ikerexxe** [comment]
Thanks and good work!

**Pull request merged**
