### PR TITLE
Ci build

### PR DESCRIPTION
**Pull request by ikerexxe**

### CODE REVIEW

**Comment by ikerexxe** [comment]
@alejandro-colomar do you know what would be the equivalent of `ULONG_WIDTH` for alpine linux (musl)?

**Comment by cgzones** [comment]
`sizeof(unsigned long) * 8`?

**Comment by alejandro-colomar** [comment]
We can add the following to defines.h:

#ifndef ULONG_WIDTH
#define ULONG_WIDTH (sizeof(unsigned long) * CHAR_BIT)
#endif


This macro will be defined by C23.

--
<http://www.alejandro-colomar.es/>

**Comment by ikerexxe** [comment]
That's good. I've added a commit for it and I think I got the DCO right.

**Comment by alejandro-colomar** [comment]
Yep, that LGTM.

--
<http://www.alejandro-colomar.es/>

**Comment by alejandro-colomar** [comment]
Just a minor OCD thing: I'd put two blank lines between includes and
defines, and also two between defines and prototypes. :)

And I found a bad typo of mine while reviewing this: bit_ceil_wrapul() should
call bit_ceilul() rather than itself.  Can you please fix it here?  Thanks
for fixing my bugs :D

--
<http://www.alejandro-colomar.es/>

**Comment by ikerexxe** [comment]
Fixed. I opened https://github.com/shadow-maint/shadow/pull/661 to track that work.

**Comment by hallyn** [comment]
> @hallyn @alejandro-colomar do you know how I can fix the debian failure? `libbsd-dev` is already installed but it seems like something went wrong

I think you need pkgconf so autoconf can figure out that libbsd is there :)

**Comment by ikerexxe** [comment]
Ok, I think this is ready for review.

**Pull request merged**
