### PR TITLE
release 4.16.0-rc1

### PR DESCRIPTION
**Pull request by hallyn**

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
I propose merging this first:

-  <https://github.com/shadow-maint/shadow/pull/998>

(it's already approved.)

**Comment by hallyn** [comment]
> I propose merging this first:
> 
>     * [Remove support for rlogind in login(1), that is, remove the '-r' flag #998](https://github.com/shadow-maint/shadow/pull/998)
> 
> 
> (it's already approved.)

Oh, I thought you actually specifically did NOT want that merged until after release?

**Comment by hallyn** [comment]
Merged, and this pr rebased.

**Comment by hallyn** [comment]
'make dist' was giving me tons of tar errors, so I added a configure.ac change to fix those.

**Comment by alejandro-colomar** [comment]
> > I propose merging this first:
> > ```
> > * [Remove support for rlogind in login(1), that is, remove the '-r' flag #998](https://github.com/shadow-maint/shadow/pull/998)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (it's already approved.)
> 
> Oh, I thought you actually specifically did NOT want that merged until after release?

I did not, as you say, because master didn't have any breaking changes, so we could ask users to jump from 4.15x to 4.16.0.  Since we now have breaking changes in libsubid, I guess I can forget about that possibility.

I think I'll continue maintaining 4.15.x.  When 4.16.0 is released, I'll fork right before the first breaking change, and release 4.15.2 from there.

**Pull request merged**
