### PR TITLE
l10n(zh_TW): update translations

### PR DESCRIPTION
**Pull request by pan93412**
almost retranslate.

### CODE REVIEW

**Comment by pan93412** [comment]
@hallyn could you help me merge it to master? thanks you a lot! :)

**Comment by hallyn** [comment]
Hi,

thanks for the patch.

I don't understand why there are 6 patches.  Is there any functional reason for it?  Do you mind if I squash them all into a single patch?

**Comment by pan93412** [comment]
> Hi,
> 
> thanks for the patch.
> 
> I don't understand why there are 6 patches. Is there any functional reason for it? Do you mind if I squash them all into a single patch?

Oh sorry, just squash them.

**Comment by pan93412** [comment]
@hallyn I've squash it, and you can merge it without additional operations.

**Comment by hallyn** [comment]
Thank you!

**Pull request merged**
