### PR TITLE
Groupmod fixes

### PR DESCRIPTION
**Pull request by alejandro-colomar**
This is a preparation patch before some more fixes.  I found some problems in this file, which are not yet addressed by these fixes.  This is only cleaning up so that the more important fixes are more readable.

@hallyn  @ikerexxe  I need to add functions that are usable in the entire project; we've seen that some parts of the project don't use libmisc, right?  In which library should I put them?  Or can we make the entire project depend on libmisc?

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
Changes: added link to PR in commit message

**Review by ikerexxe — APPROVED** [review]
LGTM

> @hallyn @ikerexxe I need to add functions that are usable in the entire project; we've seen that some parts of the project don't use libmisc, right? In which library should I put them? Or can we make the entire project depend on libmisc?

I think it's fine to add those general functions in libmisc and make the entire project depend on this library.

**Comment by alejandro-colomar** [comment]
> LGTM

Thanks!

> 
> > @hallyn @ikerexxe I need to add functions that are usable in the entire project; we've seen that some parts of the project don't use libmisc, right? In which library should I put them? Or can we make the entire project depend on libmisc?
> 
> I think it's fine to add those general functions in libmisc and make the entire project depend on this library.

Could you please do that step of making libmisc globally available?  I have no idea of the organization of the project.  I'll start writing patches that don't need that, while I wait for that to be done.

**Comment by ikerexxe** [comment]
Unfortunately, I don't think I'll have time this year, but I'll try to accommodate some time.

**Pull request merged**
