### PR TITLE
fix add segmentation fault  chpasswd -s 1

### PR DESCRIPTION
**Pull request by wyj611**
https://github.com/shadow-maint/shadow/pull/745
Why not fix chpasswd？

### CODE REVIEW

**Comment by wyj611** [comment]
> #745
Why not fix chpasswd？

**Comment by hallyn** [comment]
I don't see a segfault in master branch.  Is there a specific set of build flags I'd need to hit this?  (I also don't see where in the code we would be dereferencing a NULL cryptmethod)

**Comment by wyj611** [comment]
> I don't see a segfault in master branch. Is there a specific set of build flags I'd need to hit this? (I also don't see where in the code we would be dereferencing a NULL cryptmethod)

Referring to https://github.com/shadow-maint/shadow/pull/745, my environment did have the following error
image

**Comment by hallyn** [comment]
> > I don't see a segfault in master branch. Is there a specific set of build flags I'd need to hit this? (I also don't see where in the code we would be dereferencing a NULL cryptmethod)
> 
> Referring to #745, my environment did have the following error image

What version of shadow was that?  My guess is it did not have 

```
commit 9cdb5251b6c30487a7d935a1a7827f493249479d
Author: juyin <zhuyan34@huawei.com>
Date:   Sat Apr 2 11:48:51 2022 +0800

    chpasswd: add IS_CRYPT_METHOD
```

**Comment by wyj611** [comment]
> > > I don't see a segfault in master branch. Is there a specific set of build flags I'd need to hit this? (I also don't see where in the code we would be dereferencing a NULL cryptmethod)
> > 
> > 
> > Referring to #745, my environment did have the following error image
> 
> What version of shadow was that? My guess is it did not have
> 
> ```
> commit 9cdb5251b6c30487a7d935a1a7827f493249479d
> Author: juyin <zhuyan34@huawei.com>
> Date:   Sat Apr 2 11:48:51 2022 +0800
> 
>     chpasswd: add IS_CRYPT_METHOD
> ```

**Pull request closed without merging**
