### PR TITLE
tests/run_some: make sure unshared root user can descend build dir

### PR DESCRIPTION
**Pull request by hallyn**
This was causing errors in my local testing in vms.

### CODE REVIEW

**Comment by hallyn** [comment]
We *could* try to re-set the perms after the test, but a) that'd be more fragile and b) we've always said the tests are destructive.

**Comment by alejandro-colomar** [comment]
LGTM.

**Comment by alejandro-colomar** [comment]
On Fri, Jun 28, 2024 at 09:05:43AM GMT, Serge Hallyn wrote:
> @hallyn requested your review on: shadow-maint/shadow#1034 tests/run_some: make sure unshared root user can descend build dir.

Was this the problem we had about set -x?  I see all CI passing now.  :)

> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/shadow-maint/shadow/pull/1034#event-13333697633
> You are receiving this because your review was requested.
> 
> Message ID: ***@***.***>

-- 
<https://www.alejandro-colomar.es/>

**Comment by hallyn** [comment]
> On Fri, Jun 28, 2024 at 09:05:43AM GMT, Serge Hallyn wrote: @hallyn requested your review on: [shadow-maint/shadow#1034](https://github.com/shadow-maint/shadow/pull/1034) tests/run_some: make sure unshared root user can descend build dir.
> Was this the problem we had about set -x? I see all CI passing now. :)
> […](#)
> -- Reply to this email directly or view it on GitHub: [#1034 (comment)](https://github.com/shadow-maint/shadow/pull/1034#event-13333697633) You are receiving this because your review was requested. Message ID: ***@***.***>
> -- <https://www.alejandro-colomar.es/>

No - that was a problem in the debian salsa ci, not here in the upstream github repo.

We'll see when Chris merges this stuff whether the problems still hit, or whether it was all spurious :)

**Pull request merged**
