### PR TITLE
Fix parentheses in configure.ac

### LINKED ISSUE #419: configure.ac: mismatched parentheses
The line https://github.com/shadow-maint/shadow/blob/master/configure.ac#L348:
 
> AS_IF([test "$with_su" != "no"], AC_DEFINE(WITH_SU, 1, [Build with su])])

has an unmatched `]`.

This is upstream and in version 4.9.

### PR DESCRIPTION
**Pull request by AZaugg**
Closes #419

### CODE REVIEW

**Review by vapier — APPROVED** [review]
thx!

**Comment by ikerexxe** [comment]
Can you also reference the issue that you are fixing on the commit? Apart from that everything looks good to me.

**Comment by AZaugg** [comment]
OK, updated the commit message to incude link to github issue

**Comment by hallyn** [comment]
Thank you.

**Pull request merged**
