### PR TITLE
lib, libmisc: Move source files to lib (where their headers were)

### PR DESCRIPTION
**Pull request by alejandro-colomar**
```
Scripted change:

$ find lib/ -type f \
| grep '\.h$' \
| sed 's,lib/,libmisc/,' \
| sed 's,\.h$,.c,' \
| xargs find 2>/dev/null \
| xargs mv -t lib/;

Plus updating the Makefiles.
```

Closes: <https://github.com/shadow-maint/shadow/issues/791>
Closes: <https://bugs.gentoo.org/912446>
Reported-by: Christian Bricart @cbricart
Reported-by: Robert Marmorstein
Cc: Sam James @thesamesam 
Cc: Michael Vetter @jubalh

### CODE REVIEW

**Comment by jubalh** [comment]
As mentioned on IRC I'm not sure why we have lib vs libmisc. But the change looks fine to me. I also applied it as a test to our openSUSE package and it builds fine.

**Comment by jubalh** [comment]
This PR also (kind of) related to https://github.com/shadow-maint/shadow/issues/763#issuecomment-1664383425, https://github.com/shadow-maint/shadow/pull/776 and https://github.com/shadow-maint/shadow/commit/d0518cc250afeaceb772a7f50a900cfc9b3ab937.

**Comment by alejandro-colomar** [comment]
Changes:

-  Update commit message

```
$ git range-diff HEAD^ 8fd9b712 HEAD
1:  8fd9b712 ! 1:  ccd8586f lib, libmisc: Move source files to lib (where their headers were)
    @@ Commit message
     
         Closes: (hopefully) <https://github.com/shadow-maint/shadow/issues/791>
         Closes: (hopefully) <https://bugs.gentoo.org/912446>
    +    Link: <https://github.com/shadow-maint/shadow/issues/763#issuecomment-1664383425>
    +    Link: <https://github.com/shadow-maint/shadow/pull/776>
         Reported-by: Christian Bricart <christian@bricart.de>
         Reported-by: Robert Marmorstein <robert@marmorstein.org>
         Cc: Sam James <sam@gentoo.org>
    -    Cc: Michael Vetter <jubalh@iodoru.org>
    +    Tested-by: Michael Vetter <jubalh@iodoru.org>
    +    Acked-by: Michael Vetter <jubalh@iodoru.org>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
      ## lib/Makefile.am ##
```

**Comment by alejandro-colomar** [comment]
Changes:

-  Update commit message
```
$ git range-diff master gh/gentoo gentoo 
1:  ccd8586f ! 1:  c56a406c lib, libmisc: Move source files to lib (where their headers were)
    @@ Commit message
         Reported-by: Christian Bricart <christian@bricart.de>
         Reported-by: Robert Marmorstein <robert@marmorstein.org>
         Cc: Sam James <sam@gentoo.org>
    +    [ jubalh tested the openSUSE package ]
         Tested-by: Michael Vetter <jubalh@iodoru.org>
         Acked-by: Michael Vetter <jubalh@iodoru.org>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
```

**Comment by alejandro-colomar** [comment]
I converted to draft until it gets tested by Gentoo people, to avoid accidentally merging it before that happens.

**Comment by alejandro-colomar** [comment]
changes:

-  Update commit message.

```
$ git range-diff master c56a406c gentoo 
1:  c56a406c ! 1:  dd64713b lib, libmisc: Move source files to lib (where their headers were)
    @@ Commit message
     
         Plus updating the Makefiles.
     
    -    Closes: (hopefully) <https://github.com/shadow-maint/shadow/issues/791>
    -    Closes: (hopefully) <https://bugs.gentoo.org/912446>
    +    Closes: <https://github.com/shadow-maint/shadow/issues/791>
    +    Closes: <https://bugs.gentoo.org/912446>
         Link: <https://github.com/shadow-maint/shadow/issues/763#issuecomment-1664383425>
         Link: <https://github.com/shadow-maint/shadow/pull/776>
    +    Link: <https://github.com/shadow-maint/shadow/commit/d0518cc250afeaceb772a7f50a900cfc9b3ab937>
         Reported-by: Christian Bricart <christian@bricart.de>
         Reported-by: Robert Marmorstein <robert@marmorstein.org>
         Cc: Sam James <sam@gentoo.org>
         [ jubalh tested the openSUSE package ]
         Tested-by: Michael Vetter <jubalh@iodoru.org>
         Acked-by: Michael Vetter <jubalh@iodoru.org>
    +    [ Robert F. tested the Gentoo package ]
    +    Tested-by: Robert Förster <Dessa@gmake.de>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
      ## lib/Makefile.am ##
```

It seems we're ready to go.  :)

**Comment by SoapGentoo** [comment]
I still get failures on arm32:
```
/bin/sh ../libtool  --tag=CC   --mode=link armv7a-unknown-linux-gnueabihf-gcc -isystem /usr/armv7a-unknown-linux-gnueabihf/usr/include/bsd -DLIBBSD_OVERLAY  -O2 -pipe -fomit-frame-pointer  -Wl,-O1 -Wl,--as-needed -o passwd passwd.o  ../libmisc/libmisc.la ../lib/libshadow.la  -lpam -lpam_misc      -ldl -lbsd 
libtool: link: armv7a-unknown-linux-gnueabihf-gcc -isystem /usr/armv7a-unknown-linux-gnueabihf/usr/include/bsd -DLIBBSD_OVERLAY -O2 -pipe -fomit-frame-pointer -Wl,-O1 -o passwd passwd.o  -Wl,--as-needed ../libmisc/.libs/libmisc.a -lcrypt ../lib/.libs/libshadow.a -lpam -lpam_misc -ldl -lbsd
/usr/libexec/gcc/armv7a-unknown-linux-gnueabihf/ld: ../lib/.libs/libshadow.a(libshadow_la-encrypt.o): in function `pw_encrypt':
encrypt.c:(.text+0xc): undefined reference to `crypt'
collect2: error: ld returned 1 exit status
```

**Comment by alejandro-colomar** [comment]
Hmmm, that one seems different.  It's not a function defined in shadow utils, but rather one from a third party library.

It would be interesting if you can bisect that problem.

**Comment by alejandro-colomar** [comment]
> I still get failures on arm32:
> 
> ```
> /bin/sh ../libtool  --tag=CC   --mode=link armv7a-unknown-linux-gnueabihf-gcc -isystem /usr/armv7a-unknown-linux-gnueabihf/usr/include/bsd -DLIBBSD_OVERLAY  -O2 -pipe -fomit-frame-pointer  -Wl,-O1 -Wl,--as-needed -o passwd passwd.o  ../libmisc/libmisc.la ../lib/libshadow.la  -lpam -lpam_misc      -ldl -lbsd 
> libtool: link: armv7a-unknown-linux-gnueabihf-gcc -isystem /usr/armv7a-unknown-linux-gnueabihf/usr/include/bsd -DLIBBSD_OVERLAY -O2 -pipe -fomit-frame-pointer -Wl,-O1 -o passwd passwd.o  -Wl,--as-needed ../libmisc/.libs/libmisc.a -lcrypt ../lib/.libs/libshadow.a -lpam -lpam_misc -ldl -lbsd
> /usr/libexec/gcc/armv7a-unknown-linux-gnueabihf/ld: ../lib/.libs/libshadow.a(libshadow_la-encrypt.o): in function `pw_encrypt':
> encrypt.c:(.text+0xc): undefined reference to `crypt'
> collect2: error: ld returned 1 exit status
> ```

See the end of the command line above:

```sh
... -lcrypt ../lib/.libs/libshadow.a -lpam -lpam_misc -ldl -lbsd
```

Since libshadow has a reference to crypt(3), it should request another -lcrypt after it.
Here's the call:

```c
lib/encrypt.c:26:	cp = crypt (clear, salt);
```

I can confirm it's a build system bug.  And can confirm I'm innocent of that one :)
It's an independent (although similar) bug.  What I'm surprised is that it hadn't been discovered until this release.

I'll see if I can find a solution to that.

But this PR is ready to be merged.

Thanks!

**Comment by thesamesam** [comment]
Looks okay but I think we need to sort out some of this overengineering with the internal lib layout in future.

**Comment by ikerexxe** [comment]
> As mentioned on IRC I'm not sure why we have lib vs libmisc. But the change looks fine to me. I also applied it as a test to our openSUSE package and it builds fine.

I have the same problem. Before proceeding to approve the changes, @hallyn can you shed some light regarding this topic?

**Comment by alejandro-colomar** [comment]
@ikerexxe 

I don't know for sure, but by looking at the kind of files that are in lib and libmisc, it seems that lib is for stuff closely related to shadow, while libmisc is more for generic string APIs.

But I think that's an unnecessary difference, since we don't package those libs, so I think we can just merge the libs.

The patches have been tested by Gentoo people, so I'd go ahead.  It's a simplification, which is usually a good thing.

**Comment by hallyn** [comment]
> > As mentioned on IRC I'm not sure why we have lib vs libmisc. But the change looks fine to me. I also applied it as a test to our openSUSE package and it builds fine.
> 
> I have the same problem. Before proceeding to approve the changes, @hallyn can you shed some light regarding this topic?

No, I really cannot explain why there is libmisc and libshadow.  That far predates any version control that I can find, and I'm quite certain predates this millenium.  I assume that it was originally an attempt to keep the size of some of the binaries down when statically linked.

**Review by hallyn — APPROVED** [review]

**Comment by SoapGentoo** [comment]
Fortunately modern linkers only pick from static libraries what they need, hence I hope we can obliterate `libmisc`

**Review by ikerexxe — APPROVED** [review]
LGTM. Thanks for the patch!

> No, I really cannot explain why there is libmisc and libshadow. That far predates any version control that I can find, and I'm quite certain predates this millenium. I assume that it was originally an attempt to keep the size of some of the binaries down when statically linked.

Then, let's get rid of it

**Comment by alejandro-colomar** [comment]
Done :)

```
$ git range-diff master..gh/gentoo2 shadow/master..gentoo2
1:  68d6ef2a < -:  -------- lib, libmisc: Move source files to lib (where their headers were)
2:  a7bf3c35 ! 1:  c5cb1f4a lib: Merge libmisc into libshadow
    @@ Commit message
         lib: Merge libmisc into libshadow
     
         The separation was unnecessary, and caused build problems.  Let's go
    -    wild and remove the library.  The files are moved to libshadow.
    +    wild and obliterate the library.  The files are moved to libshadow.
     
         Scripted change:
     
    @@ Commit message
         Cc: Robert Förster <Dessa@gmake.de>
         [ soap tested the Gentoo package ]
         Tested-by: David Seifert <soap@gentoo.org>
    +    Cc: <lslebodn@fedoraproject.org>
    +    Acked-by: Serge Hallyn <serge@hallyn.com>
    +    Acked-by: Iker Pedrosa <ipedrosa@redhat.com>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
      ## .gitignore ##
```

**Pull request merged**
