### PR TITLE
update Polish translation

### PR DESCRIPTION
**Pull request by m4sk1n**

### CODE REVIEW

**Comment by hallyn** [comment]
Thank you very much!

**Comment by m4sk1n** [comment]
No problem!

**Comment by crayxt** [comment]
It is non of my business, of course, but why have you deleted the credits line?
```
-# Polish translation for shadow.
-# Copyright (C) 1999 Free Software Foundation, Inc.
-# Arkadiusz Miśkiewicz <misiek@misiek.eu.org>, 1999.
-# Jakub Bogusz <qboosh@pld-linux.org>, 2003-2004.
-# Tomasz Kłoczko <kloczek@pld.org.pl>, 2004-2006
-#
```

**Comment by m4sk1n** [comment]
Sorry, I forgot about it... I used GlotPress and I haven't added it after exporting.

**Comment by hallyn** [comment]
Would you mind posting a new PR to add those back in?

I thought I had manually removed such a FSF copyright line removal, but clearly it wasn't in this patch...

**Comment by glensc** [comment]
i've created #54 to fix the copyright issue

but seems this PR has even more issues, and i think it should be reverted completely:
- fatal errors with messed up newlines
- no information where these translations originated, are they even newer or just commit from outdated shadow version?

/cc @hallyn

**Comment by wking** [comment]
On Mon, Dec 05, 2016 at 02:33:42PM -0800, Elan Ruusamäe wrote:
> - fatal errors with messed up newlines

More detail on reproducing these in [1].

[1]: https://github.com/shadow-maint/shadow/pull/17#issuecomment-264618693

**Comment by glensc** [comment]
made some statistics whether this PR changes are authentic at all

4.4 release:
```
$ msgfmt --statistics pl.po
211 translated messages, 179 fuzzy translations, 199 untranslated messages.
```

after this PR with `"\n"` -> `""` replacements and few other manual fixes:
```
$ msgfmt --statistics pl.po
477 translated messages, 110 untranslated messages.
```

so the numeric statistics are better, but have not looked closer because polish is not my language.

ideally the translations should be pulled from some translation system, here's no information where those changes were pulled in.

**Pull request merged**
