### PR TITLE
usermod: fix alphabetical order in help message

### PR DESCRIPTION
**Pull request by matheusmbar**

### CODE REVIEW

**Comment by ikerexxe** [comment]
LGTM. Thanks for the patch.

@hallyn can you take a look at the CI errors? They aren't related with the PR changes.

**Comment by hallyn** [comment]
Yes, I noticed them last night, will take a look.

**Comment by hallyn** [comment]
@matheusmbar  do you mind rebasing on current master and force-pushing?  That should get a clean CI build with the fix for git.

**Comment by matheusmbar** [comment]
Hi @hallyn, sorry but I couldn't take some time to do that yesterday. 
Since it is merged, I believe that the rebase is not required anymore. 
Thanks for accepting it!

**Pull request merged**
